version: "2"
services:
  mongodb:
    container_name: mongodb_demo
    image: uwitech/mongodb
    volumes:
      - mongodb-data:/data/db
  dhis-db:
    container_name: fr-db_demo
    image: uwitech/postgresql
    env_file: .env
    volumes:
      - fr-pgdata:/var/lib/postgres/data
  openempi-db:
    container_name: openempi-db_demo
    image: uwitech/postgresql
    volumes:
      - cr-pgdata:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=openempi
      - POSTGRES_DB=openempi
      - POSTGRES_PASSWORD=openempi
  openmrs-postgresql-db:
    container_name: openmrs-postgresql-db
    image: uwitech/postgresql
    volumes:
      - openmrs-pgdata:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=openxds
      - POSTGRES_DB=openxds
      - POSTGRES_PASSWORD=openxds
  openmrs-mysql-db:
    container_name: openmrs-mysql-db
    image: uwitech/mysql 
    env_file: .env
    volumes:
      - openmrs-mysqldata:/var/lib/mysql/data

  ohie-il:
    depends_on:
      - mongodb
    env_file: .env
    container_name: ohie-il_demo
    image: uwitech/ohie-il
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /etc/ssl/crt:/var/openhim/crt
  ohie-il-console:
    container_name: ohie-il-console_demo
    env_file: .env
    image: uwitech/ohie-il-console
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/crt:/etc/nginx/certs
  ohie-ilr:
    container_name: ohie-ilr-demo
    env_file: .env
    image: uwitech/ohie-ilr
  ohie-fr:
    container_name: ohie-fr-demo
    env_file: .env
    image: uwitech/ohie-fr
    ports:
      - "9000:8080"
    depends_on:
      - dhis-db
  ohie-cr:
    container_name: ohie-cr-demo
    env_file: .env
    image: uwitech/ohie-cr
    ports:
      - "8081:8080"
    volumes:
      - cr-orientdata:/data
    depends_on:
      - openempi-db

  openshr:
    container_name: oshr-demo
    image: uwitech/oshr
    env_file: .env
    ports:
      - "8082:8080"
    depends_on:
      - openmrs-mysql-db
      - openmrs-postgresql-db
    environment:
      - POSTGRES_USER=openxds
      - POSTGRES_PASSWORD=openxds

volumes:
  mongodb-data:
  fr-pgdata:
  cr-pgdata:
  cr-orientdata:
  openmrs-pgdata:
  openmrs-mysqldata:

