version: "2"
services:
  mongodb:
    container_name: mongodb_demo
    image: uwitech/mongodb
    volumes:
      - mongodb-data:/data/db
  ohie-il:
    depends_on:
      - mongodb
    env_file: .env
    container_name: ohie-il_demo
    image: uwitech/ohie-il
    ports:
      - "8080:8080"
    volumes:
      - /home/user/demo-environment/openhim:/var/openhim
    command: openhim-core --conf=/var/openhim/core.json --cluster=auto
  ohie-il-console:
    container_name: ohie-il-console_demo
    env_file: .env
    image: uwitech/ohie-il-console
    ports:
      - "80:80"

volumes:
  mongodb-data:
