version: "2"
services:
  mongodb:
    container_name: mongodb_demo
    image: uwitech/mongodb
    volumes:
      - mongodb-data:/data/db
  dhis-db:
    container_name: fr-db_demo
    image: uwitech/postgresql
    env_file: .env
    volumes:
      - fr-pgdata:/var/lib/postgres/data
  ohie-il:
    depends_on:
      - mongodb
    env_file: .env
    container_name: ohie-il_demo
    image: uwitech/ohie-il
    ports:
      - "8080:8080"
  ohie-il-console:
    container_name: ohie-il-console_demo
    env_file: .env
    image: uwitech/ohie-il-console
    ports:
      - "80:80"
  ohie-irl:
    container_name: ohie-ilr-demo
    env_file: .env
    image: uwitech/ohie-ilr
    ports:
      - "8984:8984"
  ohie-fr:
    container_name: ohie-fr-demo
    env_file: .env
    image: uwitech/ohie-fr
    ports:
      - "9000:8080"

volumes:
  mongodb-data:
  fr-pgdata:
